export const WORD_EDITOR = '#PagesContainer';
export const EDITABLE_WORD_EDITOR = '#PagesContainer[contenteditable="true"]';
export const WAC_LAUNCH_FORM = 'form[target^="WacFrame"]';
export const RENDERED_PAGE = '.Page';
export const RENDERED_PARAGRAPH = '.ParagraphTextContent';
export const CANVAS_PARAGRAPH = '.CanvasParagraph';
export const SAVE_STATUS = '#SaveStatusButton';
export const MODE_SWITCHER = '#ModeSwitcher';
export const FIND_INPUT = '#FindSearchBoxV2';
export const REPLACE_INPUT = '#ReplaceSearchBoxV2';
export const FIND_FILTER = '#navigationTab3-panel button[aria-label="Filter"]';
export const FIND_PANEL = '#navigationTab3-panel';
export const FIND_RESULT = '[data-automation-type="SearchResult"]';
export const NEXT_FIND_RESULT = '#NextSearchResult';
export const REPLACE_BUTTON = '#ReplaceButton';
export const REPLACE_ALL_BUTTON = '#ReplaceAllButton';
export const NAVIGATION_HEADINGS_TAB = '#navigationTab1';
export const NAVIGATION_HEADINGS_PANEL = '#navigationTab1-panel';
export const NAVIGATION_HEADING = '[data-automation-id="navigationPaneHeadingButton"]';
export const NAVIGATION_CLOSE = '#TaskPaneActionButtonFindReplaceTaskPane';
export const DOCUMENT_TITLE = '[data-unique-id="CommitNewDocumentTitle-input"]';
export const WORD_COUNT = '#ShowWordCountDialog';
export const RENDERED_LINK = '#PagesContainer a.Hyperlink, #PagesContainer a[href]';
export const RENDERED_TABLE = '#PagesContainer table, #PagesContainer [role="table"]';
export const COMMENTS_BUTTON = '#ShowCommentsTopBar';
export const NEW_COMMENT_BUTTON = '#NewComment-Floatie';
